name: Render and deploy Quarto files
on:
  push:
    branches: [main]
jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: quarto-dev/quarto-actions/setup@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbformat matplotlib seaborn plotly pandas numpy
    - name: Render Quarto Project
      run: quarto render index.qmd
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
